version: "3"
services:
  nifi:
    image: apache/nifi
    container_name: nifi
    ports:
      # Interface Nifi
      - "8080:8080"
      # Request with Python
      - "5000:5000"
    volumes:
      - /opt/nifi:/opt/nifi/nifi-current/treinamento_nifi

